from pathlib import Path
from typing import Union

from fastapi import FastAPI, Depends, Request
from sqlalchemy import func
from starlette.middleware.cors import CORSMiddleware

from database import get_db
from sqlalchemy.orm import Session
from models import CaseBreakdown, SankeyFilter

import pandas as pd
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates

app = FastAPI()
# Base.metadata.create_all(bind=engine)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# app.mount("/{rest_of_path: path}/{rest_of_path2: path}", StaticFiles(directory="build", html=True), name="static")


def serve_react_app(build_dir: Union[Path, str]) -> FastAPI:
    """Serves a React application in the root directory `/`

    Args:
        app: FastAPI application instance
        build_dir: React build directory (generated by `yarn build` or
            `npm run build`)

    Returns:
        FastAPI: instance with the react application added
    """
    if isinstance(build_dir, str):
        build_dir = Path(build_dir)

    app.mount(
        "/static/",
        StaticFiles(directory=build_dir / "static"),
        name="React App static files",
    )
    templates = Jinja2Templates(directory=build_dir.as_posix())

    @app.get("/{full_path:path}")
    async def serve_react_app(request: Request, full_path: str):
        """Serve the react app
        `full_path` variable is necessary to serve each possible endpoint with
        `index.html` file in order to be compatible with `react-router-dom
        """
        return templates.TemplateResponse("index.html", {"request": request})

    return app

path_to_react_app_build_dir = './build'
# app = serve_react_app(path_to_react_app_build_dir)

@app.post("/sankey-data/")
def get_sankey_data(filters: SankeyFilter, db: Session = Depends(get_db)):
    query = db.query(
        CaseBreakdown.source,
        CaseBreakdown.target,
        func.sum(CaseBreakdown.metric).label('total_metric')
    )

    if filters.County:
        query = query.filter(CaseBreakdown.County == filters.County)
    if filters.SubCounty:
        query = query.filter(CaseBreakdown.SubCounty == filters.SubCounty)
    if filters.Agency:
        query = query.filter(CaseBreakdown.Agency == filters.Agency)
    if filters.Partner:
        query = query.filter(CaseBreakdown.Partner == filters.Partner)
    if filters.CohortYearMonth:
        query = query.filter(CaseBreakdown.CohortYearMonth == filters.CohortYearMonth)

    query = query.group_by(CaseBreakdown.source, CaseBreakdown.target)
    data = query.all()

    df = pd.DataFrame([{
        'source': d.source,
        'target': d.target,
        'metric': d.total_metric
    } for d in data])

    print(df['source'].tolist().index(row['source']) for _, row in df.iterrows())
    # Transforming the data for Highcharts Sankey
    sankey_data = [
        {"from": record.source, "to": record.target, "weight": record.total_metric}
        for record in data
    ]

    return {"sankeyData": sankey_data}


@app.get("/")
async def root():
    return {"message": "Hello World"}


@app.get("/hello/{name}")
async def say_hello(name: str):
    return {"message": f"Hello {name}"}
